Move from sys_errlist in test
- error: ‘sys_errlist’ was not declared in this scope
- Just printing the error number now.
- Some helpful discussion is at
  https://github.com/fish-shell/fish-shell/issues/1830

Change-Id: I01c22131dbedeb9c761591c94af5f80c54e8288d